sudo: false
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - pip install --upgrade pip
install:
  - pip install pep8
  - python setup.py install
script:
  - python setup.py test
  - pep8
after_success:
  - coveralls