sudo: false
language: python
python:
  - "2.7"
before_install:
  - pip install pytest pytest-cov coveralls
install:
  - python setup.py install
script:
  - python -m py.test -v --cov=flask_z3950 tests/
after_success:
  - pip install coveralls
  - coveralls