sudo: false
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - pip install pytest pytest-cov coveralls pep8
install:
  - python setup.py install
script:
  - python setup.py test
  - pep8
after_success:
  - pip install coveralls
  - coveralls